import React, { useState, useEffect } from 'react';
import { Bell, Mail, CheckCircle, AlertCircle, Send, RefreshCw, Sparkles, ShieldCheck, DollarSign } from 'lucide-react';
import { formatETB } from '../utils';

interface RevenueAlertWidgetProps {
  todayRevenue: number;
}

export default function RevenueAlertWidget({ todayRevenue }: RevenueAlertWidgetProps) {
  const [threshold, setThreshold] = useState<number>(() => {
    const saved = localStorage.getItem('revenue_alert_threshold');
    return saved ? parseFloat(saved) : 10000;
  });

  const [adminEmail, setAdminEmail] = useState<string>(() => {
    return localStorage.getItem('admin_alert_email') || 'jemalfano030@gmail.com';
  });

  const [autoEmailEnabled, setAutoEmailEnabled] = useState<boolean>(() => {
    const saved = localStorage.getItem('revenue_auto_email_enabled');
    return saved !== null ? saved === 'true' : true;
  });

  const [isSending, setIsSending] = useState(false);
  const [alertStatus, setAlertStatus] = useState<{ success: boolean; message: string } | null>(null);

  // Save settings when changed
  const handleThresholdChange = (val: number) => {
    const num = Math.max(100, val);
    setThreshold(num);
    localStorage.setItem('revenue_alert_threshold', num.toString());
  };

  const handleEmailChange = (email: string) => {
    setAdminEmail(email);
    localStorage.setItem('admin_alert_email', email);
  };

  const handleToggleAutoEmail = () => {
    const next = !autoEmailEnabled;
    setAutoEmailEnabled(next);
    localStorage.setItem('revenue_auto_email_enabled', next.toString());
  };

  const sendNotificationEmail = async (isTest: boolean = false) => {
    setIsSending(true);
    setAlertStatus(null);

    const todayDate = new Date().toLocaleDateString(undefined, { weekday: 'long', year: 'numeric', month: 'long', day: 'numeric' });

    const emailPayload = {
      to: adminEmail,
      subject: isTest 
        ? `[TEST ALERT] IresoJ Digital CSC Revenue System Test` 
        : `[REVENUE TARGET REACHED] Daily Revenue Exceeded ${formatETB(threshold)}!`,
      text: isTest
        ? `Hello Administrator,\n\nThis is a verified test alert from your IresoJ Digital CSC Command Center.\n\nCurrent Today's Revenue: ${formatETB(todayRevenue)}\nSet Alert Threshold: ${formatETB(threshold)}\nTarget Email: ${adminEmail}\n\nSystem functioning normally at IresoJ Digital CSC Kore.`
        : `CONGRATULATIONS ADMINISTRATOR!\n\nYour business has officially reached/exceeded the daily revenue threshold for ${todayDate}.\n\n• Today's Revenue: ${formatETB(todayRevenue)}\n• Configured Threshold: ${formatETB(threshold)}\n• Alert Email Recipient: ${adminEmail}\n\nKeep up the great work!\nIresoJ Digital CSC Computer Services`,
      html: `
        <div style="font-family: sans-serif; padding: 20px; color: #1e293b; max-width: 600px; border: 1px solid #e2e8f0; rounded: 16px;">
          <h2 style="color: #0ea5e9; margin-top: 0;">🚀 IresoJ Digital CSC Revenue Alert</h2>
          <p style="font-size: 14px;">Daily Financial Target Status Report</p>
          <hr style="border: none; border-top: 1px solid #e2e8f0; margin: 15px 0;" />
          <div style="background-color: #f8fafc; padding: 15px; border-radius: 12px; margin-bottom: 15px;">
            <p style="margin: 5px 0;"><strong>Status:</strong> ${isTest ? '🧪 Test Email Verification' : '🔥 Daily Revenue Target Exceeded!'}</p>
            <p style="margin: 5px 0;"><strong>Current Today's Revenue:</strong> <span style="color: #10b981; font-weight: bold; font-size: 18px;">${formatETB(todayRevenue)}</span></p>
            <p style="margin: 5px 0;"><strong>Target Threshold:</strong> ${formatETB(threshold)}</p>
            <p style="margin: 5px 0;"><strong>Target Recipient:</strong> ${adminEmail}</p>
          </div>
          <p style="font-size: 12px; color: #64748b;">Automated real-time notification generated by IresoJ Digital CSC Command Center.</p>
        </div>
      `
    };

    try {
      const res = await fetch('/api/send-email', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify(emailPayload)
      });

      const data = await res.json();
      if (res.ok && data.success) {
        setAlertStatus({
          success: true,
          message: isTest 
            ? `Test alert email successfully dispatched to ${adminEmail}!` 
            : `Automated revenue threshold alert dispatched to ${adminEmail}!`
        });
      } else {
        setAlertStatus({
          success: false,
          message: data.error || 'Failed to dispatch email via API route.'
        });
      }
    } catch (err: any) {
      setAlertStatus({
        success: false,
        message: err.message || 'Network error while attempting email dispatch.'
      });
    } finally {
      setIsSending(false);
    }
  };

  // Auto trigger check when revenue threshold is crossed
  useEffect(() => {
    if (!autoEmailEnabled || todayRevenue < threshold || todayRevenue === 0) return;

    const todayStr = new Date().toISOString().split('T')[0];
    const sessionKey = `revenue_alert_dispatched_${todayStr}_${threshold}`;

    if (!sessionStorage.getItem(sessionKey)) {
      sessionStorage.setItem(sessionKey, 'true');
      sendNotificationEmail(false);
    }
  }, [todayRevenue, threshold, autoEmailEnabled]);

  const percentProgress = Math.min(100, Math.round((todayRevenue / threshold) * 100));
  const isExceeded = todayRevenue >= threshold && threshold > 0;

  return (
    <div className="bg-white dark:bg-slate-900 rounded-3xl p-6 border border-slate-100 dark:border-slate-800 shadow-sm space-y-6 transition-colors">
      
      {/* Header */}
      <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-4 pb-4 border-b border-slate-100 dark:border-slate-800">
        <div className="flex items-center gap-3">
          <div className={`p-2.5 rounded-2xl ${isExceeded ? 'bg-emerald-50 text-emerald-600 dark:bg-emerald-950/60 dark:text-emerald-400' : 'bg-sky-50 text-sky-600 dark:bg-sky-950/60 dark:text-sky-400'}`}>
            <Bell className="w-5 h-5" />
          </div>
          <div>
            <div className="flex items-center gap-2">
              <h3 className="font-display font-extrabold text-base text-slate-900 dark:text-white">
                Revenue Alert Threshold
              </h3>
              {isExceeded ? (
                <span className="px-2.5 py-0.5 rounded-full text-[10px] font-black uppercase tracking-wider bg-emerald-500/15 text-emerald-700 dark:bg-emerald-500/20 dark:text-emerald-400 border border-emerald-500/30">
                  Target Reached ({percentProgress}%)
                </span>
              ) : (
                <span className="px-2.5 py-0.5 rounded-full text-[10px] font-black uppercase tracking-wider bg-sky-500/15 text-sky-700 dark:bg-sky-500/20 dark:text-sky-400 border border-sky-500/30">
                  {percentProgress}% Of Target
                </span>
              )}
            </div>
            <p className="text-xs text-slate-500 dark:text-slate-400 mt-0.5">
              Automated email notification trigger when daily revenue crosses configured threshold
            </p>
          </div>
        </div>

        {/* Auto Dispatch Toggle */}
        <button
          onClick={handleToggleAutoEmail}
          className={`flex items-center gap-2 px-3.5 py-2 rounded-2xl text-xs font-bold transition-all border cursor-pointer ${
            autoEmailEnabled
              ? 'bg-emerald-50 dark:bg-emerald-950/50 text-emerald-700 dark:text-emerald-300 border-emerald-200 dark:border-emerald-800'
              : 'bg-slate-100 dark:bg-slate-800 text-slate-500 border-slate-200 dark:border-slate-700'
          }`}
        >
          <div className={`w-2.5 h-2.5 rounded-full ${autoEmailEnabled ? 'bg-emerald-500 animate-pulse' : 'bg-slate-400'}`} />
          <span>{autoEmailEnabled ? 'Auto Email Active' : 'Auto Email Disabled'}</span>
        </button>
      </div>

      {/* Progress Bar & Current Status */}
      <div className="bg-slate-50 dark:bg-slate-800/50 rounded-2xl p-5 border border-slate-200/60 dark:border-slate-700/60 space-y-3">
        <div className="flex items-center justify-between text-xs">
          <div>
            <span className="text-slate-500 dark:text-slate-400 font-medium">Settled Revenue Today: </span>
            <strong className="text-slate-900 dark:text-white font-mono text-sm">{formatETB(todayRevenue)}</strong>
          </div>
          <div>
            <span className="text-slate-500 dark:text-slate-400 font-medium">Alert Target: </span>
            <strong className="text-slate-900 dark:text-white font-mono text-sm">{formatETB(threshold)}</strong>
          </div>
        </div>

        {/* Progress bar visual */}
        <div className="w-full h-3 bg-slate-200 dark:bg-slate-700 rounded-full overflow-hidden p-0.5">
          <div 
            className={`h-full rounded-full transition-all duration-500 ${
              isExceeded ? 'bg-emerald-500' : 'bg-sky-500'
            }`}
            style={{ width: `${percentProgress}%` }}
          />
        </div>

        {isExceeded && (
          <div className="bg-emerald-500/10 text-emerald-800 dark:text-emerald-300 p-3 rounded-xl border border-emerald-500/20 text-xs font-semibold flex items-center gap-2">
            <Sparkles className="w-4 h-4 text-emerald-600 dark:text-emerald-400 shrink-0" />
            <span>
              🔥 Threshold achieved! Today's revenue ({formatETB(todayRevenue)}) has reached or exceeded your target of {formatETB(threshold)}.
            </span>
          </div>
        )}
      </div>

      {/* Settings Input Grid */}
      <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
        <div>
          <label className="block text-[11px] font-bold text-slate-500 dark:text-slate-400 uppercase tracking-wider mb-1.5">
            Daily Revenue Threshold (ETB)
          </label>
          <div className="relative">
            <DollarSign className="absolute left-3 top-1/2 -translate-y-1/2 w-4 h-4 text-slate-400" />
            <input
              type="number"
              min={100}
              step={500}
              value={threshold}
              onChange={(e) => handleThresholdChange(parseFloat(e.target.value) || 0)}
              className="w-full pl-9 pr-4 py-2.5 bg-white dark:bg-slate-900 border border-slate-200 dark:border-slate-700 rounded-xl text-xs font-mono font-bold text-slate-900 dark:text-white focus:outline-none focus:ring-1 focus:ring-sky-500"
              placeholder="e.g. 10000"
            />
          </div>
        </div>

        <div>
          <label className="block text-[11px] font-bold text-slate-500 dark:text-slate-400 uppercase tracking-wider mb-1.5">
            Administrator Email Recipient
          </label>
          <div className="relative">
            <Mail className="absolute left-3 top-1/2 -translate-y-1/2 w-4 h-4 text-slate-400" />
            <input
              type="email"
              value={adminEmail}
              onChange={(e) => handleEmailChange(e.target.value)}
              className="w-full pl-9 pr-4 py-2.5 bg-white dark:bg-slate-900 border border-slate-200 dark:border-slate-700 rounded-xl text-xs font-mono font-bold text-slate-900 dark:text-white focus:outline-none focus:ring-1 focus:ring-sky-500"
              placeholder="jemalfano030@gmail.com"
            />
          </div>
        </div>
      </div>

      {/* Action Buttons & Status */}
      <div className="pt-2 flex flex-col sm:flex-row items-stretch sm:items-center justify-between gap-3">
        <button
          onClick={() => sendNotificationEmail(true)}
          disabled={isSending}
          className="px-4 py-2.5 bg-slate-900 dark:bg-slate-800 hover:bg-slate-800 dark:hover:bg-slate-700 text-white rounded-xl text-xs font-bold flex items-center justify-center gap-2 transition-all cursor-pointer disabled:opacity-50 shadow-xs"
        >
          {isSending ? (
            <RefreshCw className="w-4 h-4 animate-spin" />
          ) : (
            <Send className="w-4 h-4 text-sky-400" />
          )}
          <span>{isSending ? 'Sending Email Alert...' : 'Send Test Alert Email'}</span>
        </button>

        <div className="flex items-center gap-2 text-[11px] text-slate-500 dark:text-slate-400">
          <ShieldCheck className="w-4 h-4 text-emerald-500" />
          <span>Notifications routed via Express endpoint `/api/send-email`</span>
        </div>
      </div>

      {/* Alert Status Feedback */}
      {alertStatus && (
        <div className={`p-3 rounded-2xl border text-xs font-semibold flex items-center gap-2 animate-in fade-in duration-200 ${
          alertStatus.success 
            ? 'bg-emerald-50 text-emerald-800 dark:bg-emerald-950/60 dark:text-emerald-200 border-emerald-200 dark:border-emerald-800' 
            : 'bg-rose-50 text-rose-800 dark:bg-rose-950/60 dark:text-rose-200 border-rose-200 dark:border-rose-800'
        }`}>
          {alertStatus.success ? (
            <CheckCircle className="w-4 h-4 text-emerald-600 dark:text-emerald-400 shrink-0" />
          ) : (
            <AlertCircle className="w-4 h-4 text-rose-600 dark:text-rose-400 shrink-0" />
          )}
          <span>{alertStatus.message}</span>
        </div>
      )}

    </div>
  );
}
